/* ==========================================================
 * Project: Dungeon Janitors: Estate of Chaos
 * Developer: Omer Burak Ozgur
 * GitHub: https://github.com/omerburakozgur
 * ========================================================== */
using UnityEngine;
using System;

/// <summary>
/// Combat system authority responsible for applying damage, handling death events
/// and serving as a single point of truth for combat-related logic.
/// </summary>
public class CombatManager : SingletonManager<CombatManager>
{
    // Event channels such as hit VFX or audio may be added here if needed (commented out in current code)
    // [SerializeField] private VoidEventChannelSO onEnemyHitChannel;

    [Header("Juice Events")]
    [SerializeField] private VoidEventChannelSO onCameraStrikeChannel;

    /// <summary>
    /// Called by weapon systems to process a validated hit on a damageable target.
    /// Applies damage, knockback, stun parameters and notifies any interested systems.
    /// </summary>
    /// <param name="target">The interface of the receiver.</param>
    /// <param name="damage">Amount of raw damage to inflict.</param>
    /// <param name="knockbackForce">Physics force vector generated by the hit.</param>
    /// <param name="hitPoint">Center position point of the strike.</param>
    /// <param name="stunDuration">Seconds that the target will be rendered frozen.</param>
    /// <param name="knockbackDuration">Seconds that the knockback momentum will be applied.</param>
    public void ProcessPlayerHit(IDamageable target, float damage, Vector3 knockbackForce, Vector3 hitPoint, float stunDuration = 0f, float knockbackDuration = 0.2f)
    {
        if (target == null) return;
        
        // Pass parameters to target interface
        target.TakeDamage(damage, knockbackForce, hitPoint, stunDuration, knockbackDuration);

        if (FeedbackManager.Instance != null)
        {
            // Set text spawn position based on whether local hit point exists
            Vector3 textPos = (hitPoint != Vector3.zero) ? hitPoint : (target as MonoBehaviour).transform.position;
            FeedbackManager.Instance.ShowDamage(textPos, damage, false);

            // Execute hitstop effect to provide combat weight 
            FeedbackManager.Instance.TriggerHitStop(0.08f);
        }

        if (onCameraStrikeChannel != null)
        {
            onCameraStrikeChannel.Raise();
        }
    }

    /// <summary>
    /// Notifies systems when an enemy has died. Triggers loot drops and scores.
    /// </summary>
    /// <param name="enemyObj">The GameObject reference of the eliminated enemy.</param>
    public void ReportEnemyDeath(GameObject enemyObj)
    {
        if (enemyObj == null) return;

        // Default to Basic tier for MVP. 
        // If a public getter for EnemyStatsSO is added later, this can be read dynamically.
        EnemyTier tier = EnemyTier.Basic;

        if (LootManager.Instance != null)
        {
            LootManager.Instance.RequestSpawnLoot(enemyObj.transform.position, tier);
        }
    }
}